# Generated by Django 2.2.4 on 2019-09-02 11:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0017_practices_page_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('LeagueType', models.CharField(default='ECTC', max_length=100)),
                ('timing', models.CharField(default='', max_length=100)),
                ('icon', models.CharField(default='flaticon-martial-arts', max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('page_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='practices',
            name='icon',
            field=models.CharField(default='flaticon-martial-arts', max_length=100),
        ),
    ]
