# Generated by Django 2.2.4 on 2019-09-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0018_auto_20190902_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='semester',
            field=models.CharField(default='Fall', max_length=100),
        ),
    ]
