# Generated by Django 2.2.4 on 2019-09-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='id',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='Name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
