# Generated by Django 2.2.4 on 2019-09-02 00:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0003_instructor_page_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
