# Generated by Django 2.2.4 on 2019-09-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0004_auto_20190901_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='instructor_pics'),
        ),
    ]
