# Generated by Django 2.2.4 on 2019-09-02 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0007_auto_20190902_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('classyear', models.IntegerField(default=0)),
                ('course', models.IntegerField(default=0)),
                ('image', models.ImageField(default='default.jpg', upload_to='alumni_pics')),
                ('text', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='Position',
        ),
        migrations.AddField(
            model_name='officer',
            name='position',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
