# Generated by Django 2.2.4 on 2019-09-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0009_auto_20190902_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='position',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
