# Generated by Django 2.2.4 on 2019-09-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0011_auto_20190902_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='ID',
            field=models.AutoField(serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='officer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='officer',
            name='position',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
