# Generated by Django 2.2.4 on 2019-09-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0012_auto_20190902_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='rank',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
