# Generated by Django 2.2.4 on 2019-09-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0013_instructor_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='rank',
            field=models.CharField(default='', max_length=100),
        ),
    ]
