# Generated by Django 2.2.4 on 2019-09-02 10:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0015_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practices',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('days', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('icon', models.CharField(default='', max_length=100)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
