# Generated by Django 2.2.4 on 2019-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0020_majorfriend_minorfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorfriend',
            name='contribution',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
