# Generated by Django 2.2.4 on 2019-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0021_majorfriend_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorfriend',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='majorfriend',
            name='page_order',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='minorfriend',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='minorfriend',
            name='page_order',
            field=models.IntegerField(default=5000),
        ),
    ]
