# Generated by Django 2.2.4 on 2019-09-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0002_auto_20190901_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='page_order',
            field=models.IntegerField(default=0),
        ),
    ]
