# Generated by Django 2.2.4 on 2019-09-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0006_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='Position',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officer',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
