# Generated by Django 2.2.4 on 2019-09-02 10:14

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0014_auto_20190902_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('text', tinymce.models.HTMLField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
