# Generated by Django 2.2.4 on 2019-09-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdwebsite', '0016_practices'),
    ]

    operations = [
        migrations.AddField(
            model_name='practices',
            name='page_order',
            field=models.IntegerField(default=0),
        ),
    ]
